apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secret
  namespace: jitsi
type: Opaque
stringData:
  JICOFO_AUTH_PASSWORD: "change-me"
  JVB_AUTH_PASSWORD: "change-me"
  JICOFO_COMPONENT_SECRET: "change-me"
