apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - name: prosody
          image: jitsi/jvb:jvb-2.3-296-g318c08ddc-1
          ports:
            - containerPort: 5222
            - containerPort: 5280
          envFrom:
            - configMapRef:
                name: jitsi-config
            - secretRef:
                name: jitsi-secret
