apiVersion: v1
kind: Service
metadata:
  name: jitsi-web
  namespace: jitsi
spec:
  type: NodePort
  selector:
    app: jitsi-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP