apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-config
  namespace: jitsi
data:
  # ---- Network ----
  PUBLIC_URL: "http://192.168.122.65:30080"
  JVB_ADVERTISE_IPS: "192.168.122.65"
  # ---- Disable all TLS / HTTPS ----
  ENABLE_LETSENCRYPT: "0"
  DISABLE_HTTPS: "1"
  ENABLE_HTTP_REDIRECT: "0"

  # ---- XMPP / Prosody ----
  XMPP_DOMAIN: "meet.jitsi"
  XMPP_AUTH_DOMAIN: "auth.meet.jitsi"
  XMPP_MUC_DOMAIN: "muc.meet.jitsi"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.meet.jitsi"
  XMPP_GUEST_DOMAIN: "guest.meet.jitsi"
  XMPP_SERVER: "prosody"
  XMPP_BOSH_URL_BASE: "http://prosody:5280"

  # ---- JVB (Videobridge) ----
  JVB_BREWERY_MUC: "jvbbrewery"
  JVB_TCP_HARVESTER_DISABLED: "false"
  JVB_TCP_PORT: "4443"
  JVB_TCP_MAPPED_PORT: "30443"          # NodePort browsers will connect to
  JVB_STUN_SERVERS: ""                  # disable external STUN in lab
  JVB_DISABLE_STUN: "true"
  JVB_PORT: "10000"
  JVB_AUTH_USER: "jvb"

  # ---- Jicofo ----
  JICOFO_AUTH_USER: "focus"
  JICOFO_COMPONENT_SECRET: "s3cr3t"
  JICOFO_AUTH_PASSWORD: "jicofo_pass"

  # ---- General ----
  TZ: "UTC"
  ENABLE_GUESTS: "1"
  AUTH_TYPE: "none"