apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secrets
  namespace: jitsi
type: Opaque
stringData:
  JICOFO_AUTH_PASSWORD: "jicofo_pass"
  JVB_AUTH_PASSWORD: "jvb_pass"
  JICOFO_COMPONENT_SECRET: "s3cr3t"
  PROSODY_JICOFO_PASSWORD: "jicofo_pass"
  PROSODY_JVB_PASSWORD: "jvb_pass"