apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo:jicofo-1.0-1184-1
          envFrom:
            - configMapRef:
                name: jitsi-config
            - secretRef:
                name: jitsi-secret
