apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secret
  namespace: jitsi
type: Opaque
stringData:
  JICOFO_AUTH_PASSWORD: "jicofo-pass"
  JICOFO_COMPONENT_SECRET: "component-secret"
  JVB_AUTH_PASSWORD: "jvb-pass"
