apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      securityContext:
        fsGroup: 1000   # ensures volumes are group-writable by the container user
      containers:
        - name: jvb
          image: jitsi/jvb:jvb-2.3-296-g318c08ddc-1
          ports:
            - containerPort: 10000
              protocol: UDP
          envFrom:
            - configMapRef:
                name: jitsi-config
            - secretRef:
                name: jitsi-secret
          volumeMounts:
            - name: jvb-run
              mountPath: /run/jvb
            - name: jitsi-config-volume
              mountPath: /run/jvb/config/jvb.conf
              subPath: jvb.conf
      volumes:
        - name: jvb-run
          emptyDir: {}
        - name: jitsi-config-volume
          configMap:
            name: jitsi-config
